INSERT
    INTO
        emp
    VALUES
        (
            :empno
            ,:ename
            ,:job
            ,:mgr
            ,:hiredate
            ,:sal
            ,:comm
            ,:deptno
        )
